import logging
from typing import Optional

import requests

from authenticator import Authenticator
from entities import Thing


class S3IClient:
    """This is the main class for the S3I-Client. It is used to send and receive messages from the broker.

    Args:
        sender (entity): The entity which should send the message.
        auth (Authenticator): The authenticator which should be used to authenticate the sender.
        logger (Optional[logging.Logger]): The logger which should be used for logging. Defaults to the "S3I" logger.
    """

    def __init__(self, sender: Thing, auth: Authenticator, logger: Optional[logging.Logger] = logging.getLogger("S3I")):
        self.endpoint = sender
        self.authenticator = auth
        self._logger = logger

    def receive_message(self) -> requests.Response:
        """Receives the most current message from the broker."""
        headers = {}
        headers |= self.authenticator.get_auth_headers()
        self._logger.debug(f"Additional headers: {headers}")
        response = requests.get(
            f"https://broker.s3i.vswf.dev/{self.endpoint.queue}",
            headers=headers,
        )
        self._logger.debug(f"Response: {response.text}")
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as err:
            self._logger.error(f"Encountered an error while trying to receive a message: {err}")
        return response

    def send_message(self, message: str, to_endpoint: str) -> requests.Response:
        """Sends a message to the broker.

        Args:
            message (str): This is the message body which should be sent to the broker. It should be generated by the
                message builder in the message_types module.
            to_endpoint (str): This is the endpoint to which the message should be sent.

        Returns:
            response (requests.Response): The response of the broker.
        """
        headers = {}
        headers |= self.authenticator.get_auth_headers()
        self._logger.debug(f"Additional headers: {headers}")

        response = requests.post(
            f"https://broker.s3i.vswf.dev/{to_endpoint}",
            headers=headers,
            data=message,
        )
        self._logger.debug(f"Response: {response.text}")

        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as err:
            self._logger.error(f"Encountered an error while trying to send a message: {err}")

        return response
