import json
from functools import wraps
from secrets import token_hex
from typing import Callable


def _generate_identifier():
    """This method generates a message identifier for the S3I protocol. The identifier is a string in the following
    shape: s3i:********-****-****-****-************
    Hereby every * is a random character from the set [0-9a-f]. Those are randomly generated by the secrets module.
    """
    secret = token_hex(16)
    return f"s3i:{secret[:8]}-{secret[8:12]}-{secret[12:16]}-{secret[16:20]}-{secret[20:]}"


def build_request_body(func) -> Callable[..., str]:
    """This decorator is used to build the request body for a S3I message.
    Every S3I-request contains at least the following parameters:
    {
        "sender": <sender>,
        "identifier": <identifier>,
        "receivers": [<receiver1>, <receiver2>, ...]
    }
    After that, the decorator calls the decorated function and adds the result to the request body. It returns that
    formatted in JSON.

    All of those parameters should be given through the **kwargs parameter. The identifier is generated by the builder
    itself when it is not given.
    """

    @wraps(func)
    def wrapper(**kwargs) -> str:
        request_body = {"sender": kwargs.get("sender"), "identifier": _generate_identifier(),
                        "receivers": list(kwargs.get("receivers"))}
        request_body |= func(**kwargs)
        return json.dumps(request_body, separators=(",", ":"), indent=None)  # Returns a minified JSON string

    return wrapper


@build_request_body
def build_get_value_request_body(**kwargs) -> dict:
    """This method builds the requests body for a GetValueRequest in the S3I protocol. The structure of the body is as
    follows:
    {
        "sender": <sender>,
        "identifier": <identifier>,
        "receivers": [<receiver1>, <receiver2>, ...],

        "messageType": "getValueRequest",
        "replyToEndpoint": <replyToEndpoint>,
        "attributePath": <attributePath>
    }
    All of those parameters should be given through the **kwargs parameter. The identifier is generated by the builder
    itself, if it is not given. messageType is given by the builder itself. The rest of the parameters are mandatory.
    """
    return {
        "messageType": "getValueRequest",
        "replyToEndpoint": kwargs.get("replyToEndpoint"),
        "attributePath": kwargs.get("attributePath"),
    }


@build_request_body
def build_get_value_reply_body(**kwargs) -> dict:
    """This method builds the requests body for a GetValueRequest in the S3I protocol. The structure of the body is as
    follows:
    {
        "sender": <sender>,
        "identifier": <identifier>,
        "receivers": [<receiver1>, <receiver2>, ...],

        "messageType": "getValueRequest",
        "replyingToMessage": <replyingToMessage>,
        "attributePath": <attributePath>
    }
    All of those parameters should be given through the **kwargs parameter. The identifier is generated by the builder
    itself, if it is not given. messageType is given by the builder itself. The rest of the parameters are mandatory.
    """
    return {
        "messageType": "getValueReply",
        "replyingToMessage": kwargs.get("replyingToMessage"),
        "value": kwargs.get("value"),
    }
